import { test, expect } from '@playwright/test';

test.use({ timeout: 60000 });

test('test', async ({ page }) => {
  await page.goto('http://192.168.136.43/');
  await page.goto('http://192.168.136.43/user/login');
  await page.goto('http://192.168.136.43/user/login/');
  await page.getByPlaceholder('نام کاربری').click();
  await page.getByPlaceholder('نام کاربری').fill('admin');
  await page.getByPlaceholder('نام کاربری').press('Tab');
  await page.getByPlaceholder('رمزعبور').fill('admin@123');
  await page.getByPlaceholder('رمزعبور').press('Tab');
  await page.getByRole('button', { name: 'ورود' }).press('Enter');
  await page.getByRole('link', { name: 'گروه ها' }).click();
  await page.getByRole('button', { name: 'plus افزودن گروه' }).click();
  await page.getByLabel('نام').click();
  await page.getByLabel('نام').fill('aut_group');
  await page.getByLabel('نام').press('Enter');
  await page.getByRole('button', { name: 'plus افزودن گروه' }).click();
  await page.getByLabel('نام').click();
  await page.getByLabel('نام').fill('aut_group');
  await page.getByRole('button', { name: 'تایید' }).click();
  await page.locator('.ant-message-custom-content').click();
  await expect(page.locator('body')).toContainText('نام گروه تکراری است (Code: 25)');
  await page.getByLabel('نام').click();
  await page.getByLabel('نام').dblclick();
  await page.getByLabel('نام').fill('\' or \'hello\';');
  await page.getByRole('button', { name: 'تایید' }).click();
  
  await page.getByRole('row', { name: 'Toggle Row Expanded 15 \' or \'' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'تایید' }).click();
  await page.getByRole('row', { name: 'Toggle Row Expanded 14' }).locator('a').nth(1).click();
  await page.locator('form span').first().click();
  await page.getByLabel('نام').fill('aut_group2');
  await page.getByRole('button', { name: 'تایید' }).click();
  await page.getByRole('row', { name: 'Toggle Row Expanded 14' }).getByRole('img').first().click();
  await page.getByRole('row', { name: 'Toggle Row Expanded 14' }).locator('a').first().click();
  await page.getByLabel('نام زیرگروه').click();
  await page.getByLabel('نام زیرگروه').fill('aut_sg');
  await page.getByRole('button', { name: 'تایید' }).click();
  await page.getByRole('row', { name: 'Toggle Row Expanded 14' }).locator('a').first().click();
  await page.getByLabel('نام زیرگروه').click();
  await page.getByLabel('نام زیرگروه').fill('aut_sg');
  await page.getByRole('button', { name: 'تایید' }).click();
  await expect(page.locator('body')).toContainText('نام زیرگروه تکراری است (Code: 27)');
  await page.getByRole('button', { name: 'لغو' }).click();
  await page.getByRole('row', { name: 'Toggle Row Expanded 14' }).locator('a').nth(3).click();
  await page.getByLabel('نام زیرگروه').dblclick();
  await page.getByLabel('نام زیرگروه').click();
  await page.getByLabel('نام زیرگروه').click();
  await page.getByLabel('نام زیرگروه').fill('\' or hello;+_');
  await page.getByRole('button', { name: 'تایید' }).click();
  await expect(page.locator('tbody')).toContainText('\' or hello;+_');
  await page.getByRole('row', { name: 'Toggle Row Expanded 14' }).locator('a').nth(1).click();
  await page.locator('form span').first().click();
  await page.getByLabel('نام').fill('aut_group');
  await page.getByRole('button', { name: 'تایید' }).click();
  await expect(page.locator('tbody')).toContainText('زیرگروه عمومی');
  await page.getByRole('link', { name: 'پیکربندی دستگاه' }).click();
  await page.getByPlaceholder('جستجو کنید').click();
  await page.getByPlaceholder('جستجو کنید').fill('11223');
  await expect(page.getByRole('rowgroup')).toContainText('112239c1');
  await page.getByPlaceholder('جستجو کنید').click();
  await page.getByPlaceholder('جستجو کنید').fill('');
  await expect(page.getByRole('rowgroup')).toContainText('0ba8a0bc');
  await expect(page.getByRole('rowgroup')).toContainText('G1');
  await page.getByRole('link', { name: 'گروه ها' }).click();
  await expect(page.getByRole('rowgroup')).toContainText('G1');
  await page.getByRole('row', { name: 'Toggle Row Expanded 2 G1' }).locator('a').nth(1).click();
  await page.getByLabel('نام').click();
  await page.getByLabel('نام').fill('G2');
  await page.getByRole('button', { name: 'تایید' }).click();
  await page.getByRole('link', { name: 'پیکربندی دستگاه' }).click();
  await expect(page.getByRole('rowgroup')).toContainText('G2');
  await page.getByRole('link', { name: 'گروه ها' }).click();
  await page.getByRole('row', { name: 'Toggle Row Expanded 2 G2' }).locator('a').nth(1).click();
  await page.getByLabel('نام').click();
  await page.getByLabel('نام').fill('G1');
  await page.getByRole('button', { name: 'تایید' }).click();
  await expect(page.getByRole('rowgroup')).toContainText('G1');
  await page.getByRole('row', { name: 'Toggle Row Expanded 14' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'تایید' }).click();
});