import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://192.168.136.90/');
  await page.goto('http://192.168.136.90/user/login');
  await page.goto('http://192.168.136.90/user/login/');
  await page.getByPlaceholder('نام کاربری').fill('admin');
  await page.getByPlaceholder('نام کاربری').press('Tab');
  await page.getByPlaceholder('رمزعبور').fill('admin@123');
  await page.getByRole('button', { name: 'ورود' }).click();
  await expect(page.getByRole('complementary')).toContainText('مجوزها');
  await page.getByRole('link', { name: 'مجوزها' }).click();
  await page.getByRole('button', { name: 'plus مجوز جدید' }).click();
  await page.getByLabel('نام').click();
  await page.getByLabel('نام').fill('t_lic4');
  await page.getByLabel('نام').press('Tab');
  await page.getByLabel('ظرفیت').fill('4');
  await page.getByRole('button', { name: 'تایید' }).click();
  await expect(page.getByRole('rowgroup')).toContainText('t_lic4');
  await page.getByRole('button', { name: 'plus مجوز جدید' }).click();
  await page.getByLabel('نام').click();
  await page.getByLabel('نام').fill('t_lic4');
  await page.getByLabel('نام').press('Tab');
  await page.getByLabel('ظرفیت').fill('3');
  await page.getByLabel('ظرفیت').press('Tab');
  await page.getByLabel('توضیحات').press('Tab');
  await page.getByRole('button', { name: 'لغو' }).press('Tab');
  await page.getByRole('button', { name: 'تایید' }).click();
  await page.waitForTimeout(1000);
  await expect(page.locator('body')).toContainText('تغییرات موردنظر اعمال نشد (Code: 23)', {timeout: 5});
  await page.getByLabel('نام').dblclick();
  await page.getByLabel('نام').fill('t_lic4_)(*((*(&(*&');
  await page.getByRole('button', { name: 'تایید' }).click();
  await expect(page.getByRole('rowgroup')).toContainText('t_lic4_)(*((*(&(*&');
  await page.getByRole('button', { name: 'plus مجوز جدید' }).click();
  await page.getByRole('button', { name: 'تایید' }).click();
  await expect(page.locator('#name_help')).toContainText('فیلد نام اجباریست');
  await expect(page.locator('#capacity_help')).toContainText('فیلد ظرفیت اجباریست');
  await page.getByLabel('نام').click();
  await page.getByLabel('نام').fill('fgfgfg');
  await page.getByLabel('ظرفیت').click();
  await page.getByLabel('ظرفیت').fill('444444');
  await expect(page.locator('#capacity_help')).toContainText('محدودیت ظرفیت مجوز');
  await page.getByRole('button', { name: 'لغو' }).click();
  await page.getByRole('row', { name: 't_lic4_)(*((*(&(*& 3' }).locator('a').first().click();
  await page.getByLabel('نام').click();
  await page.getByLabel('نام').dblclick();
  await page.getByLabel('نام').fill('t_lic5');
  await page.getByLabel('ظرفیت').click();
  await page.getByLabel('ظرفیت').fill('5');
  await page.getByRole('button', { name: 'تایید' }).click();
  await expect(page.getByRole('rowgroup')).toContainText('t_lic5');
  await expect(page.getByRole('rowgroup')).toContainText('5');
  await page.getByRole('row', { name: 't_lic5 5' }).locator('a').first().click();
  await page.getByLabel('نام').click();
  await page.getByLabel('نام').fill('t_lic4');
  await page.getByRole('button', { name: 'تایید' }).click();
  await expect(page.locator('body')).toContainText('تغییرات موردنظر اعمال نشد (Code: 43)' , {timeout: 5000});
  await page.getByLabel('ظرفیت').click();
  await page.getByLabel('ظرفیت').fill('55555555');
  await expect(page.locator('#capacity_help')).toContainText('محدودیت ظرفیت مجوز');
  await page.getByLabel('ظرفیت').click();
  await page.getByLabel('ظرفیت').fill('');
  await expect(page.locator('#capacity_help')).toContainText('فیلد ظرفیت اجباریست');
  await page.getByRole('button', { name: 'لغو' }).click();
  await expect(page.getByRole('rowgroup')).toContainText('t_lic5');
  await expect(page.getByRole('rowgroup')).toContainText('5');
  await page.getByRole('button', { name: 'plus مجوز جدید' }).click();
  await page.getByLabel('نام').click();
  await page.getByLabel('نام').fill('super AdMin');
  await page.getByLabel('نام').press('Tab');
  await page.getByLabel('ظرفیت').fill('4');
  await page.getByRole('button', { name: 'تایید' }).click();
  await expect(page.locator('body')).toContainText('تغییرات موردنظر اعمال نشد (Code: 23)', {timeout: 10});
  await page.getByLabel('نام').click();
  await page.getByLabel('نام').fill('مدیر کل');
  await page.getByRole('button', { name: 'loading تایید' }).click();
  await page.waitForTimeout(1000);
  await expect(page.locator('body')).toContainText('تغییرات موردنظر اعمال نشد (Code: 23)' , {timeout: 5});
  await page.getByLabel('نام').click();
  await page.waitForTimeout(1000);
  await page.getByLabel('نام').fill('pages.license.superAdminLicense');
  await page.getByRole('button', { name: 'loading تایید' }).click();
  await page.waitForTimeout(1000);
  await expect(page.locator('body')).toContainText('تغییرات موردنظر اعمال نشد (Code: 23)', {timeout: 5000});
  await page.getByRole('button', { name: 'لغو' }).click();
  await page.getByPlaceholder('جستجو کنید').click();
  await page.getByPlaceholder('جستجو کنید').fill('t_lic');
  await expect(page.getByRole('rowgroup')).toContainText('t_lic4');
  await expect(page.getByRole('rowgroup')).toContainText('t_lic5');
  await page.getByPlaceholder('جستجو کنید').click();
  await page.getByPlaceholder('جستجو کنید').fill('5');
  await expect(page.getByRole('rowgroup')).toContainText('5');
  await page.getByPlaceholder('جستجو کنید').click();
  await page.getByPlaceholder('جستجو کنید').fill('');
  await page.getByRole('button', { name: 'plus مجوز جدید' }).click();
  await page.getByLabel('نام').click();
  await page.getByLabel('نام').fill('aaaa');
  await page.getByLabel('ظرفیت').click();
  await page.getByLabel('ظرفیت').fill('8');
  await page.getByRole('button', { name: 'تایید' }).click();
  await expect(page.getByRole('rowgroup')).toContainText('aaaa');
  await expect(page.getByRole('rowgroup')).toContainText('8');
  await page.getByRole('row', { name: 'aaaa 8' }).locator('a').nth(1).click();
  await page.getByText('لغوتایید').click();
  await page.getByRole('button', { name: 'تایید' }).click();
  await expect(page.locator('body')).toContainText('تغییرات با موفقیت اعمال شد');
  await page.getByRole('link', { name: 'مدیران' }).click();
  await page.getByRole('button', { name: 'plus افزودن مدیر جدید' }).click();
  await page.getByLabel('نام کاربری').click();
  await page.getByLabel('نام کاربری').fill('t_mini');
  await page.getByLabel('نام کاربری').press('Tab');
  await page.getByLabel('رمزعبور').fill('pass@123');
  await page.getByLabel('مجوز').click();
  await page.getByText('t_lic4').click();
  await page.getByRole('button', { name: 'تایید' }).click();
  await expect(page.getByRole('rowgroup')).toContainText('t_mini');
  await expect(page.getByRole('rowgroup')).toContainText('t_lic4');
  await page.getByRole('link', { name: 'مجوزها' }).click();
  await page.getByRole('row', { name: 't_lic4 4' }).getByLabel('').check();
  await page.getByRole('row', { name: 't_lic5 5' }).getByLabel('').check();
  await page.getByRole('button', { name: 'delete حذف' }).click();
  await expect(page.getByRole('dialog')).toContainText('مجوز در جای دیگری استفاده شده است');
  await page.getByRole('button', { name: 'تایید' }).click();
  await page.getByRole('link', { name: 'مدیران' }).click();
  await page.getByRole('row', { name: 't_mini t_lic4' }).locator('a').nth(3).click();
  await page.getByText('لغوتایید').click();
  //await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'تایید' }).click();
  await page.getByRole('link', { name: 'مجوزها' }).click();
  await page.getByRole('row', { name: 't_lic4 4' }).getByLabel('').check();
  await page.getByRole('button', { name: 'delete حذف' }).click();
  await expect(page.locator('body')).toContainText('تغییرات با موفقیت اعمال شد');
});